export const animalProfiles = [
    {
        id: 'dog',
        name: '강아지상',
        emoji: '🐶',
        tagline: '다정함이 먼저 닿는 부드러운 인상',
        keywords: ['다정함', '편안함', '순한 눈매', '따뜻한 미소'],
        summary: '편안하고 다정한 분위기가 먼저 느껴지는 인상입니다.',
        firstImpression: '처음 봐도 경계심을 낮추게 만드는 사람',
        smileCharm: '웃을 때 눈매와 입꼬리가 함께 풀리며 친근함이 크게 살아납니다.',
        mood: '사람들이 부드럽고 믿음직한 분위기를 느끼기 쉽습니다.',
        difference: '곰상보다 더 밝고 가벼운 친근함이 강합니다.',
        resultMessage: '부드러운 눈매와 완만한 얼굴선, 자연스러운 미소가 친근하고 다정한 분위기를 만듭니다.',
        guide: '둥근 눈매와 완만한 얼굴선이 만나 편안하고 순한 분위기를 만드는 얼굴',
        compat: ['quokka', 'bear'],
        compatText: '밝은 에너지를 편안하게 받아주는 쿼카상, 곰상과 좋은 케미를 보입니다.',
        weights: { roundFace: 0.22, eyeRoundness: 0.18, eyeSoftness: 0.18, smileCurve: 0.24, compactFeatures: 0.1, sharpJaw: -0.12 },
        commentTemplates: ['눈매가 부드럽고 둥근 편이라 편안한 인상이 잘 살아납니다.', '입꼬리 흐름이 자연스러워 다정하고 친근한 분위기가 큽니다.', '얼굴 윤곽이 날카롭기보다 완만해 강아지상 점수가 높게 나타났습니다.'],
    },
    {
        id: 'cat',
        name: '고양이상',
        emoji: '🐱',
        tagline: '차분하지만 시선이 머무는 세련된 인상',
        keywords: ['도도함', '세련됨', '날렵함', '선명한 눈매'],
        summary: '차분하지만 쉽게 잊히지 않는 세련된 인상입니다.',
        firstImpression: '말수가 적어도 분위기가 또렷한 사람',
        smileCharm: '웃을 때 차분한 인상이 부드럽게 풀리며 반전 매력이 생깁니다.',
        mood: '정돈된 이미지와 은근한 존재감이 함께 느껴집니다.',
        difference: '여우상보다 더 차분하고 절제된 분위기가 강합니다.',
        resultMessage: '길고 선명한 눈매와 정돈된 얼굴선이 도도하고 세련된 인상을 줍니다.',
        guide: '날렵한 눈매와 정돈된 얼굴선으로 세련되고 도도한 분위기가 나는 얼굴',
        compat: ['fox', 'wolf'],
        compatText: '선명한 매력을 잘 받아주는 여우상, 늑대상과 인상 조합이 또렷합니다.',
        weights: { eyeSlenderness: 0.24, eyeTailUp: 0.24, sharpJaw: 0.18, longFace: 0.08, cheekDefinition: 0.1, smileCurve: -0.06 },
        commentTemplates: ['눈의 가로 흐름이 선명해 차분하고 세련된 느낌이 있습니다.', '눈꼬리 방향이 살짝 올라간 편이라 도도한 분위기가 더해집니다.', '얼굴선이 비교적 정돈되어 고양이상과 잘 맞습니다.'],
    },
    {
        id: 'rabbit',
        name: '토끼상',
        emoji: '🐰',
        tagline: '맑고 사랑스러운 분위기가 강한 인상',
        keywords: ['맑음', '귀여움', '동그란 눈', '작은 이목구비'],
        summary: '맑고 귀여운 분위기가 강한 인상입니다.',
        firstImpression: '깨끗하고 귀여운 분위기가 먼저 보이는 사람',
        smileCharm: '웃을 때 맑은 눈매와 작은 입매가 더 사랑스럽게 보입니다.',
        mood: '가볍고 밝은 귀여움, 보호본능을 자극하는 느낌이 있습니다.',
        difference: '강아지상보다 더 맑고 오밀조밀한 귀여움이 큽니다.',
        resultMessage: '동그란 눈망울과 오밀조밀한 이목구비가 깨끗하고 귀여운 분위기를 만들어냅니다.',
        guide: '큰 눈과 오밀조밀한 이목구비로 맑고 귀여운 느낌이 강한 얼굴',
        compat: ['dog', 'quokka'],
        compatText: '부드럽게 받아주는 강아지상, 밝게 맞춰주는 쿼카상과 잘 어울립니다.',
        weights: { eyeRoundness: 0.28, bigEyes: 0.22, compactFeatures: 0.18, smallMouth: 0.12, roundFace: 0.12, sharpJaw: -0.1 },
        commentTemplates: ['눈매가 둥글게 잡혀 맑고 또렷한 느낌이 큽니다.', '이목구비가 오밀조밀하게 모인 편이라 귀여운 분위기가 살아납니다.', '강한 골격감보다 부드러운 인상이 앞서 토끼상 점수가 높게 나타났습니다.'],
    },
    {
        id: 'fox',
        name: '여우상',
        emoji: '🦊',
        tagline: '영리하고 날렵한 분위기가 돋보이는 인상',
        keywords: ['영리함', '날렵함', '올라간 눈꼬리', '선명함'],
        summary: '날렵하고 영리한 분위기가 돋보이는 인상입니다.',
        firstImpression: '쉽게 읽히지 않는 매력이 있는 사람',
        smileCharm: '웃을 때 선명한 인상이 부드럽게 바뀌며 매력이 커집니다.',
        mood: '센스 있고 빠른 이미지, 시선을 끄는 세련미가 느껴집니다.',
        difference: '고양이상보다 더 적극적이고 선명한 인상이 강합니다.',
        resultMessage: '긴 눈매와 올라간 눈꼬리, 선명한 턱선이 날렵하고 인상적인 분위기를 만듭니다.',
        guide: '올라간 눈꼬리와 선명한 얼굴선으로 영리하고 매력적인 분위기가 나는 얼굴',
        compat: ['cat', 'wolf'],
        compatText: '비슷한 선명함을 가진 고양이상, 늑대상과 날카로운 케미가 좋습니다.',
        weights: { eyeSlenderness: 0.28, eyeTailUp: 0.24, sharpJaw: 0.18, longFace: 0.1, cheekDefinition: 0.12, eyeSoftness: -0.06 },
        commentTemplates: ['눈매가 길고 날렵하게 읽혀 영리한 인상이 강합니다.', '눈꼬리의 상승감이 여우상 특유의 선명한 분위기와 잘 맞습니다.', '턱선과 광대 흐름이 또렷해 결과 점수에 반영됐습니다.'],
    },
    {
        id: 'deer',
        name: '사슴상',
        emoji: '🦌',
        tagline: '맑고 여린 분위기가 자연스러운 인상',
        keywords: ['청순함', '큰 눈', '여린 선', '차분함'],
        summary: '맑고 여린 분위기가 자연스럽게 보이는 인상입니다.',
        firstImpression: '조용하지만 깨끗한 분위기가 오래 남는 사람',
        smileCharm: '웃을 때 차분함이 따뜻하게 풀리며 청순한 느낌이 강해집니다.',
        mood: '부드럽고 섬세한 분위기, 맑은 첫인상을 줍니다.',
        difference: '토끼상보다 더 차분하고 여린 분위기가 큽니다.',
        resultMessage: '큰 눈과 여린 얼굴선, 차분한 분위기가 부드럽고 깨끗한 인상을 만들어냅니다.',
        guide: '큰 눈과 여린 얼굴선으로 맑고 차분한 분위기가 느껴지는 얼굴',
        compat: ['rabbit', 'horse'],
        compatText: '맑은 결이 비슷한 토끼상, 차분한 말상과 안정적인 케미를 보입니다.',
        weights: { bigEyes: 0.3, eyeSoftness: 0.2, longFace: 0.1, smallMouth: 0.1, sharpJaw: -0.14, cheekDefinition: 0.06 },
        commentTemplates: ['눈 크기와 부드러운 눈매가 맑은 분위기를 만듭니다.', '얼굴선이 강하기보다 여린 쪽에 가까워 사슴상과 잘 맞습니다.', '전체적으로 차분하고 깨끗한 인상이 점수에 반영됐습니다.'],
    },
    {
        id: 'bear',
        name: '곰상',
        emoji: '🐻',
        tagline: '포근하고 든든한 안정감이 있는 인상',
        keywords: ['포근함', '넓은 얼굴', '둥근 윤곽', '묵직함'],
        summary: '포근하고 든든한 느낌이 중심인 인상입니다.',
        firstImpression: '가까이 있으면 편안할 것 같은 사람',
        smileCharm: '웃을 때 든든한 인상이 부드럽게 풀리며 따뜻함이 커집니다.',
        mood: '차분한 안정감과 포근한 에너지가 함께 느껴집니다.',
        difference: '강아지상보다 더 묵직하고 안정적인 인상이 강합니다.',
        resultMessage: '넓고 둥근 얼굴형과 안정적인 이목구비가 묵직하면서도 따뜻한 분위기를 만듭니다.',
        guide: '넓고 둥근 윤곽이 포근하고 안정적인 느낌을 주는 얼굴',
        compat: ['dog', 'quokka'],
        compatText: '부드러운 에너지가 맞는 강아지상, 밝은 쿼카상과 편안한 케미가 좋습니다.',
        weights: { wideFace: 0.26, roundFace: 0.22, softJaw: 0.16, broadFeatures: 0.12, smileCurve: 0.08, eyeSlenderness: -0.08 },
        commentTemplates: ['얼굴의 가로 폭과 둥근 윤곽이 안정적으로 보입니다.', '턱선이 날카롭기보다 부드러워 포근한 느낌이 큽니다.', '이목구비가 작게 모이기보다 여유 있게 배치되어 곰상 점수가 올라갔습니다.'],
    },
    {
        id: 'wolf',
        name: '늑대상',
        emoji: '🐺',
        tagline: '강하고 또렷한 카리스마가 있는 인상',
        keywords: ['카리스마', '강한 눈빛', '각진 턱선', '선 굵음'],
        summary: '강하고 또렷한 분위기가 먼저 느껴지는 인상입니다.',
        firstImpression: '조용해도 존재감이 큰 사람',
        smileCharm: '웃을 때 강한 인상이 풀리며 의외의 부드러움이 드러납니다.',
        mood: '단단하고 집중감 있는 이미지, 쉽게 흔들리지 않는 분위기가 있습니다.',
        difference: '공룡상보다 더 차분하고 날카로운 카리스마가 강합니다.',
        resultMessage: '강한 눈빛과 각진 턱선, 선 굵은 이목구비가 단단하고 인상적인 분위기를 만듭니다.',
        guide: '강한 눈빛과 선명한 하관이 만나 카리스마가 느껴지는 얼굴',
        compat: ['fox', 'cat'],
        compatText: '선명한 눈매 계열인 여우상, 고양이상과 차분하지만 강한 케미가 납니다.',
        weights: { sharpJaw: 0.28, eyeSlenderness: 0.18, browIntensity: 0.16, broadFeatures: 0.12, longFace: 0.1, smileCurve: -0.08 },
        commentTemplates: ['턱선과 얼굴 하관이 비교적 또렷해 강한 인상이 느껴집니다.', '눈매가 부드럽기보다 집중감 있게 읽혀 카리스마가 살아납니다.', '선 굵은 이목구비 흐름이 늑대상 점수에 반영됐습니다.'],
    },
    {
        id: 'monkey',
        name: '원숭이상',
        emoji: '🐵',
        tagline: '표정이 풍부하고 생동감 있는 인상',
        keywords: ['장난기', '생동감', '표정감', '활발함'],
        summary: '표정이 풍부하고 생동감 있는 인상입니다.',
        firstImpression: '대화하면 분위기가 금방 살아날 것 같은 사람',
        smileCharm: '웃을 때 눈과 입 주변 표정이 크게 살아나며 장난기가 보입니다.',
        mood: '밝고 민첩한 에너지, 친해지고 싶은 분위기가 느껴집니다.',
        difference: '쿼카상보다 더 장난스럽고 표현감이 큽니다.',
        resultMessage: '눈과 입의 표현감이 살아 있고 얼굴 중심부의 에너지가 밝고 장난기 있는 분위기를 만듭니다.',
        guide: '눈과 입 주변 표정감이 풍부해 활발하고 장난기 있는 얼굴',
        compat: ['quokka', 'dog'],
        compatText: '밝은 텐션이 맞는 쿼카상, 다정하게 받아주는 강아지상과 잘 맞습니다.',
        weights: { expressiveMouth: 0.24, smileCurve: 0.18, compactFeatures: 0.14, cheekDefinition: 0.12, bigEyes: 0.1, broadFeatures: 0.08 },
        commentTemplates: ['눈과 입 주변의 변화가 잘 보여 표정감이 풍부하게 느껴집니다.', '입매가 생동감 있게 잡혀 밝고 장난기 있는 인상을 줍니다.', '얼굴 중심부의 특징이 또렷해 원숭이상과 잘 연결됩니다.'],
    },
    {
        id: 'horse',
        name: '말상',
        emoji: '🐴',
        tagline: '시원하고 우아한 세로 비율의 인상',
        keywords: ['긴 얼굴형', '우아함', '시원한 비율', '차분함'],
        summary: '세로 비율이 길고 시원한 분위기가 있는 인상입니다.',
        firstImpression: '단정하고 고급스러운 분위기가 있는 사람',
        smileCharm: '웃을 때 긴 얼굴 비율이 부드럽게 풀리며 안정감이 커집니다.',
        mood: '차분하고 시원한 이미지, 성숙한 분위기를 줍니다.',
        difference: '낙타상보다 더 밝고 단정한 우아함이 강합니다.',
        resultMessage: '긴 얼굴형과 안정적인 세로 비율이 단정하면서도 고급스러운 분위기를 만들어냅니다.',
        guide: '세로 비율이 길고 시원해 단정하고 우아한 분위기가 나는 얼굴',
        compat: ['deer', 'camel'],
        compatText: '차분한 사슴상, 깊이 있는 낙타상과 안정적인 조합을 만듭니다.',
        weights: { longFace: 0.34, longMidface: 0.2, broadFeatures: 0.1, eyeSoftness: 0.08, smallMouth: 0.06, roundFace: -0.12 },
        commentTemplates: ['얼굴의 세로 비율이 비교적 길게 나타나 시원한 인상을 줍니다.', '중안부 흐름이 안정적이라 우아한 분위기가 살아납니다.', '둥근 귀여움보다 길고 단정한 비율이 말상 점수에 반영됐습니다.'],
    },
    {
        id: 'dinosaur',
        name: '공룡상',
        emoji: '🦖',
        tagline: '한 번 보면 기억에 남는 존재감 있는 인상',
        keywords: ['존재감', '뚜렷한 골격', '강한 턱선', '개성'],
        summary: '한 번 보면 기억에 남는 존재감 있는 인상입니다.',
        firstImpression: '인상이 선명해서 쉽게 잊히지 않는 사람',
        smileCharm: '웃을 때 강한 골격감과 부드러운 표정이 대비되어 매력이 생깁니다.',
        mood: '개성 있고 힘 있는 이미지, 또렷한 존재감이 느껴집니다.',
        difference: '늑대상보다 더 골격감과 개성의 인상이 강합니다.',
        resultMessage: '뚜렷한 골격과 강한 턱선, 선명한 이목구비가 존재감 있는 분위기를 만듭니다.',
        guide: '뚜렷한 골격과 선 굵은 이목구비로 개성 있는 존재감이 나는 얼굴',
        compat: ['wolf', 'fox'],
        compatText: '존재감이 비슷한 늑대상, 여우상과 인상적인 케미를 만듭니다.',
        weights: { sharpJaw: 0.3, browIntensity: 0.18, cheekDefinition: 0.16, broadFeatures: 0.14, longFace: 0.08, eyeSoftness: -0.08 },
        commentTemplates: ['턱선과 얼굴 골격의 존재감이 비교적 크게 나타납니다.', '이목구비의 대비가 선명해 개성 있는 인상으로 읽힙니다.', '부드러운 인상보다 뚜렷한 구조감이 공룡상 점수를 끌어올렸습니다.'],
    },
    {
        id: 'camel',
        name: '낙타상',
        emoji: '🐫',
        tagline: '차분하고 깊이 있는 여운이 남는 인상',
        keywords: ['긴 중안부', '나른함', '깊은 눈매', '묵직함'],
        summary: '차분하고 깊이 있는 분위기가 남는 인상입니다.',
        firstImpression: '여유롭고 쉽게 흔들리지 않을 것 같은 사람',
        smileCharm: '웃을 때 묵직한 인상이 느슨해지며 편안한 매력이 생깁니다.',
        mood: '나른하지만 깊이 있는 분위기, 독특한 안정감이 느껴집니다.',
        difference: '말상보다 더 나른하고 깊은 분위기가 강합니다.',
        resultMessage: '긴 중안부와 나른한 눈매, 묵직한 얼굴선이 여유롭고 독특한 분위기를 만듭니다.',
        guide: '긴 중안부와 깊은 눈매로 차분하고 묵직한 분위기가 나는 얼굴',
        compat: ['horse', 'bear'],
        compatText: '차분한 말상, 포근한 곰상과 느긋하고 안정적인 케미가 좋습니다.',
        weights: { longMidface: 0.3, longFace: 0.18, eyeSlenderness: 0.14, browIntensity: 0.1, wideEyeGap: 0.08, smileCurve: -0.08 },
        commentTemplates: ['중안부 비율이 길게 나타나 차분하고 깊은 분위기가 있습니다.', '눈매가 또렷하면서도 살짝 나른하게 읽힙니다.', '밝은 미소형보다 묵직한 인상이 낙타상 점수에 반영됐습니다.'],
    },
    {
        id: 'quokka',
        name: '쿼카상',
        emoji: '🐾',
        tagline: '밝고 무해한 미소가 매력적인 인상',
        keywords: ['밝음', '무해함', '미소', '친근함'],
        summary: '밝고 무해한 미소가 매력적인 인상입니다.',
        firstImpression: '보고 있으면 기분이 편해지는 사람',
        smileCharm: '웃을 때 입꼬리와 눈매가 함께 올라가 밝은 에너지가 커집니다.',
        mood: '친근하고 긍정적인 분위기, 주변을 편안하게 만드는 느낌이 있습니다.',
        difference: '원숭이상보다 더 부드럽고 무해한 밝음이 강합니다.',
        resultMessage: '자연스럽게 올라간 입꼬리와 부드러운 눈매가 밝고 무해한 분위기를 만들어냅니다.',
        guide: '올라간 입꼬리와 부드러운 눈매로 밝고 무해한 느낌이 강한 얼굴',
        compat: ['dog', 'bear'],
        compatText: '당신의 밝은 에너지를 편안하게 받아주는 강아지상, 곰상과 좋은 케미를 보입니다.',
        weights: { smileCurve: 0.3, mouthCornerUp: 0.22, eyeSoftness: 0.18, roundFace: 0.12, compactFeatures: 0.08, sharpJaw: -0.1 },
        commentTemplates: ['입꼬리가 자연스럽게 올라가 밝은 인상이 강합니다.', '눈매가 부드럽게 읽혀 무해하고 편안한 분위기를 만듭니다.', '얼굴 윤곽도 날카롭기보다 완만해 쿼카상 점수가 높게 나타났습니다.'],
    },
];

export const featureLabels = {
    roundFace: '둥근 얼굴형',
    longFace: '긴 얼굴형',
    wideFace: '넓은 얼굴형',
    sharpJaw: '선명한 턱선',
    softJaw: '부드러운 턱선',
    cheekDefinition: '또렷한 광대 흐름',
    bigEyes: '큰 눈',
    eyeRoundness: '둥근 눈망울',
    eyeSlenderness: '길고 날렵한 눈매',
    eyeTailUp: '올라간 눈꼬리',
    eyeSoftness: '부드러운 눈매',
    wideEyeGap: '넓은 눈 사이 간격',
    longMidface: '긴 중안부',
    smallMouth: '작은 입매',
    expressiveMouth: '표현감 있는 입매',
    smileCurve: '밝은 미소',
    mouthCornerUp: '올라간 입꼬리',
    compactFeatures: '오밀조밀한 이목구비',
    broadFeatures: '큼직한 이목구비',
    browIntensity: '강한 눈썹과 눈빛',
};

export const quizQuestions = [
    {
        question: '처음 만난 사람이 자주 말하는 내 분위기는?',
        options: [
            { label: '순하고 편해 보인다', animal: 'dog' },
            { label: '차분하고 도도해 보인다', animal: 'cat' },
            { label: '밝고 귀여워 보인다', animal: 'quokka' },
            { label: '선명하고 강해 보인다', animal: 'wolf' },
        ],
    },
    {
        question: '웃지 않을 때 내 인상에 가까운 쪽은?',
        options: [
            { label: '맑고 차분한 편', animal: 'deer' },
            { label: '날렵하고 세련된 편', animal: 'fox' },
            { label: '포근하고 안정적인 편', animal: 'bear' },
            { label: '개성 있고 존재감 있는 편', animal: 'dinosaur' },
        ],
    },
    {
        question: '내가 좋아하는 첫인상 키워드는?',
        options: [
            { label: '우아함', animal: 'horse' },
            { label: '귀여움', animal: 'rabbit' },
            { label: '생동감', animal: 'monkey' },
            { label: '깊이감', animal: 'camel' },
        ],
    },
];
